wandb_version: 1

seed:
  desc: null
  value: 42
device:
  desc: null
  value: cpu
data_dir:
  desc: null
  value: /opt/ml/input/data/
asset_dir:
  desc: null
  value: asset/
file_name:
  desc: null
  value: train_data.csv
model_dir:
  desc: null
  value: models/
model_name:
  desc: null
  value: best_model.pt
output_dir:
  desc: null
  value: outputs/
test_file_name:
  desc: null
  value: test_data.csv
max_seq_len:
  desc: null
  value: 20
num_workers:
  desc: null
  value: 1
cat_cols:
  desc: null
  value:
  - assessmentItemID
  - testId
  - KnowledgeTag
con_cols:
  desc: null
  value:
  - user_answer_mean
  - ass_answer_mean
  - testid_answer_mean
  - tag_answer_mean
  - user_answer_acc_per
  - reverse_answer_cumsum
  - testid_cumsum
  - tag_cumsum
  - relative_answer_score
  - elapsed
  - elapsed_cumsum
  - normalized_elapsed
  - elapsed_type_mean
  - relative_elapsed
  - elapsed_pca
  - elapsed_lda
  - rolling_mean_time
tgt_col:
  desc: null
  value:
  - answerCode
hidden_dim:
  desc: null
  value: 64
n_layers:
  desc: null
  value: 2
n_heads:
  desc: null
  value: 2
drop_out:
  desc: null
  value: 0.2
n_epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.0001
clip_grad:
  desc: null
  value: 10
patience:
  desc: null
  value: 5
log_steps:
  desc: null
  value: 50
model:
  desc: null
  value: lastquery
optimizer:
  desc: null
  value: adam
scheduler:
  desc: null
  value: plateau
n_assessmentItemID:
  desc: null
  value: 9455
n_testId:
  desc: null
  value: 1538
n_KnowledgeTag:
  desc: null
  value: 913
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705434768.739295
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.1
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
